"""多智能体系统。

无需API KEY的免费大模型多智能体系统。
"""

from taolib.testing.multi_agent.agents import (
    AgentFactory,
    AgentTemplate,
    BaseAgent,
    MainAgent,
    SubAgentWrapper,
    get_agent_factory,
    get_all_templates,
    get_template,
    set_agent_factory,
)
from taolib.testing.multi_agent.errors import (
    AgentError,
    LLMError,
    ModelUnavailableError,
    MultiAgentError,
    SkillError,
    TaskError,
)
from taolib.testing.multi_agent.llm import (
    LLMManager,
    LoadBalancer,
    ModelRegistry,
    get_llm_manager,
    set_llm_manager,
)
from taolib.testing.multi_agent.models import (
    AgentBase,
    AgentCapability,
    AgentConfig,
    AgentCreate,
    AgentDocument,
    AgentResponse,
    AgentStatus,
    AgentTemplate,
    AgentType,
    AgentUpdate,
    LoadBalanceConfig,
    LoadBalanceStrategy,
    Message,
    MessagePayload,
    MessageType,
    ModelConfig,
    ModelInstance,
    ModelProvider,
    ModelStatus,
    ModelStats,
    SkillBase,
    SkillCreate,
    SkillDocument,
    SkillEvaluation,
    SkillParameter,
    SkillResponse,
    SkillStatus,
    SkillTestResult,
    SkillType,
    SkillUpdate,
    SubTask,
    TaskBase,
    TaskConstraint,
    TaskCreate,
    TaskDocument,
    TaskProgress,
    TaskResponse,
    TaskResult,
    TaskStatus,
    TaskUpdate,
)
from taolib.testing.multi_agent.skills import (
    BaseSkill,
    CodeGenerationSkill,
    DataAnalysisSkill,
    Skill,
    SkillExecutionContext,
    SkillManager,
    SkillRegistry,
    TextSummarizationSkill,
    TranslationSkill,
    get_preset_skills,
    get_skill_manager,
    get_skill_registry,
    set_skill_manager,
    set_skill_registry,
)

__version__ = "0.1.0"

__all__ = [
    # Version
    "__version__",
    # Errors
    "MultiAgentError",
    "AgentError",
    "TaskError",
    "SkillError",
    "LLMError",
    "ModelUnavailableError",
    # Agents
    "BaseAgent",
    "MainAgent",
    "SubAgentWrapper",
    "AgentFactory",
    "get_agent_factory",
    "set_agent_factory",
    # Templates
    "AgentTemplate",
    "get_template",
    "get_all_templates",
    # Skills
    "Skill",
    "BaseSkill",
    "SkillExecutionContext",
    "SkillRegistry",
    "get_skill_registry",
    "set_skill_registry",
    "SkillManager",
    "get_skill_manager",
    "set_skill_manager",
    "TextSummarizationSkill",
    "CodeGenerationSkill",
    "TranslationSkill",
    "DataAnalysisSkill",
    "get_preset_skills",
    # LLM
    "LLMManager",
    "LoadBalancer",
    "ModelRegistry",
    "get_llm_manager",
    "set_llm_manager",
    # Models - Enums
    "AgentStatus",
    "AgentType",
    "TaskStatus",
    "SkillType",
    "SkillStatus",
    "MessageType",
    "ModelProvider",
    "ModelStatus",
    "LoadBalanceStrategy",
    # Models - Agent
    "AgentCapability",
    "AgentConfig",
    "AgentBase",
    "AgentCreate",
    "AgentUpdate",
    "AgentResponse",
    "AgentDocument",
    # Models - Task
    "TaskConstraint",
    "TaskProgress",
    "TaskResult",
    "SubTask",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskDocument",
    # Models - Skill
    "SkillParameter",
    "SkillTestResult",
    "SkillEvaluation",
    "SkillBase",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "SkillDocument",
    # Models - Message
    "MessagePayload",
    "Message",
    # Models - LLM
    "ModelConfig",
    "ModelStats",
    "ModelInstance",
    "LoadBalanceConfig",
]
